import "@/app/globals.css";
import Sidebar from "../adminComponents/Sidebar";
import styles from "./page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={styles.dashboardContainer}>
      <Sidebar />
      <div className={styles.content}>{children}</div>
    </div>
  );
}
